 fetch('https://corona.lmao.ninja/v2/countries/jordan') .then((response) => { return response.json(); }) .then((data) => { console.log(data); document.getElementById("cases").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases").innerHTML
= data.todayCases.toLocaleString(); document.getElementById("death").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered").innerHTML = data.recovered.toLocaleString();
document.getElementById("todayRecovered").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/palestine') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-1").innerHTML
= data.cases.toLocaleString(); document.getElementById("todayCases-1").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-1").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-1").innerHTML = data.todayDeaths.toLocaleString();
document.getElementById("recovered-1").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-1").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/syria') .then((pla) =>
{ return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-2").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-2").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-2").innerHTML
= data.deaths.toLocaleString(); document.getElementById("todayDeaths-2").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-2").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-2").innerHTML
= data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/lebanon') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-3").innerHTML = data.cases.toLocaleString();
document.getElementById("todayCases-3").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-3").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-3").innerHTML = data.todayDeaths.toLocaleString();
document.getElementById("recovered-3").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-3").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/yemen') .then((pla) =>
{ return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-4").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-4").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-4").innerHTML
= data.deaths.toLocaleString(); document.getElementById("todayDeaths-4").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-4").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-4").innerHTML
= data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/qatar') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-5").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-5").innerHTML
= data.todayCases.toLocaleString(); document.getElementById("death-5").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-5").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-5").innerHTML =
data.recovered.toLocaleString(); document.getElementById("todayRecovered-5").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/bahrain') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data);
document.getElementById("cases-6").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-6").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-6").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-6").innerHTML
= data.todayDeaths.toLocaleString(); document.getElementById("recovered-6").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-6").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/oman')
.then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-7").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-7").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-7").innerHTML
= data.deaths.toLocaleString(); document.getElementById("todayDeaths-7").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-7").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-7").innerHTML
= data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/kuwait') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-8").innerHTML = data.cases.toLocaleString();
document.getElementById("todayCases-8").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-8").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-8").innerHTML = data.todayDeaths.toLocaleString();
document.getElementById("recovered-8").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-8").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/turkey') .then((pla) =>
{ return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-9").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-9").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-9").innerHTML
= data.deaths.toLocaleString(); document.getElementById("todayDeaths-9").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-9").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-9").innerHTML
= data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/iran') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-10").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-10").innerHTML
= data.todayCases.toLocaleString(); document.getElementById("death-10").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-10").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-10").innerHTML
= data.recovered.toLocaleString(); document.getElementById("todayRecovered-8").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/egypt') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data);
document.getElementById("cases-11").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-11").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-11").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-11").innerHTML
= data.todayDeaths.toLocaleString(); document.getElementById("recovered-11").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-11").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/uae')
.then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-12").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-12").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-12").innerHTML
= data.deaths.toLocaleString(); document.getElementById("todayDeaths-12").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-12").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-12").innerHTML
= data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/iraq') .then((pla) => { return pla.json(); }) .then((data) => { console.log(data); document.getElementById("cases-13").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-13").innerHTML
= data.todayCases.toLocaleString(); document.getElementById("death-13").innerHTML = data.deaths.toLocaleString(); document.getElementById("todayDeaths-13").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-13").innerHTML
= data.recovered.toLocaleString(); document.getElementById("todayRecovered-13").innerHTML = data.todayRecovered.toLocaleString(); }); fetch('https://corona.lmao.ninja/v2/countries/saudi arabia') .then((pla) => { return pla.json(); }) .then((data) => {
console.log(data); document.getElementById("cases-14").innerHTML = data.cases.toLocaleString(); document.getElementById("todayCases-14").innerHTML = data.todayCases.toLocaleString(); document.getElementById("death-14").innerHTML = data.deaths.toLocaleString();
document.getElementById("todayDeaths-14").innerHTML = data.todayDeaths.toLocaleString(); document.getElementById("recovered-14").innerHTML = data.recovered.toLocaleString(); document.getElementById("todayRecovered-14").innerHTML = data.todayRecovered.toLocaleString();
});



